# Distribution / packaging
*.pyc
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# Package manager
node_modules/
package-lock.json

# Serverless directories
.serverless

test_data/
