resolver: lts-15.1
packages:
- .
extra-deps:
- linklater-4.0.0.2
- serverless-haskell-0.10.1
- wai-3.2.2.1
- warp-3.3.9
- mtl-2.2.2
- split-0.2.3.4
- amazonka-dynamodb-1.6.1
- amazonka-core-1.6.1
- amazonka-xray-1.6.1
- dynamodb-simple-0.6.0.2
- pretty-show-1.10
- aeson-pretty-0.8.8
- ghc-prim-0.5.3
- uuid-1.3.13
- hal-0.4.1
- websockets-0.12.7.0
- slack-web-0.2.0.11
- array-0.5.4.0
